routes:
  /signup/:
    template: signup
    # data: page.signup # When active data will be taken from the  "/signup/" page
  /signin/:
    template: signin
    # data: page.signin # When active data will be taken from the  "/signin/" page

collections:
  /:
    permalink: /{slug}/
    template: index
  /writings/:
    permalink: /{slug}/
    template: writings
    # data: page.writings # When active data will be taken from the  "/writings/" page

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
